DROP SCHEMA hospital;
CREATE SCHEMA hospital;
USE hospital;

CREATE TABLE EMPLOYEE(
EmployeeID INT,
Name VARCHAR(80),
Address VARCHAR(80),
JobType VARCHAR(80),
Specialty VARCHAR(80),
Ward INT,
Cost INT,
Rank INT,
PracticeInfo VARCHAR(160),
PRIMARY KEY(EmployeeID),
KEY(Specialty)
);
CREATE TABLE CONDITIONS(
Conditions INT NOT NULL,
Specialty VARCHAR(80),

TimeToCure INT,
Cost INT,
PRIMARY KEY(Conditions),
FOREIGN KEY(Specialty) REFERENCES EMPLOYEE(Specialty)
);

CREATE TABLE INSURANCE
(InsuranceID INT(20) NOT NULL,
Agent VARCHAR(20),
Deductible INT(20),
MaxAllowable INT(20),
PRIMARY KEY (InsuranceID)
);

CREATE TABLE PATIENT(
PatientID INT NOT NULL,
Name VARCHAR(80) ,
Phone VARCHAR(80),
Address VARCHAR(80),
NextofKin VARCHAR(80),
LivingWill VARCHAR(160),
InsuranceID INT(20) NOT NULL,
Conditions INT NOT NULL,
PRIMARY KEY(PatientID),
FOREIGN KEY(Conditions) REFERENCES CONDITIONS(Conditions),
FOREIGN KEY(InsuranceID) REFERENCES INSURANCE(InsuranceID)
);

CREATE TABLE ROOM(
Room INT NOT NULL,
Ward INT,
Price INT,
PRIMARY KEY(Room)
);

CREATE TABLE SCHEDULES(
Date VARCHAR(80) NOT NULL,
Time VARCHAR(80) NOT NULL,
Room INT,
PatientID INT,
SurgeonID INT,
TechID INT,
NurseID INT,
PRIMARY KEY(Date,Time, Room),
FOREIGN KEY(Room) REFERENCES ROOM(Room),
FOREIGN KEY(PatientID) REFERENCES PATIENT(PatientID),
FOREIGN KEY(SurgeonID) REFERENCES EMPLOYEE(EmployeeID),
FOREIGN KEY(TechID) REFERENCES EMPLOYEE(EmployeeID),
FOREIGN KEY(NurseID) REFERENCES EMPLOYEE(EmployeeID)
);

